rpc:
  serverPort: 9039
  serializer: json
  name: wangxing
  identify: true
  version: 2.1
  serviceGroup: beijing
  srsm: true
  limiterKey: tokenBucketRateLimiter
  timeInterval: 1000
  maxTokens: 100
